const errorTypes = {
  ERROR_BAD_REQUEST: 400,
  ERROR_UNAUTHORIZED: 401,
  ERROR_FORBIDDEN: 403,
  ERROR_NOT_FOUND: 404,

  ERROR_INVALID_ARGUMENTS: 400,
  ERROR_DATA: 400,

  ERROR_INTERNAL_SERVER_ERROR: 500,
};

export default errorTypes;
